#!/usr/bin/env python3

#HALP Discard all local changes, with confirmation step.

from common import run

def main():
    run(['git', 'status'])
    input('Press enter to permanently lose all these changes.')
    run(['git', 'reset', '--hard'])

if '__main__' == __name__:
    main()
