#!/usr/bin/env python3

#HALP Discard all local changes, with confirmation step.

import subprocess

def main():
    subprocess.run(['git', 'status'], check = True)
    input('Press enter to permanently lose all these changes.')
    subprocess.run(['git', 'reset', '--hard'], check = True)

if '__main__' == __name__:
    main()
