#!/usr/bin/env python3

#HALP Pull master and releases with automatic stash and switch.

from common import nicely, isgitpol, publicbranches, run, stderr

def main():
    def pullthem():
        for b in publicbranches():
            if isgitpol(b): # TODO: Exclude my (public) branches only.
                stderr("Skip: %s" % b)
                continue
            run(['git', 'checkout', b])
            run(['git', 'pull'])
    nicely(pullthem)

if '__main__' == __name__:
    main()
