#!/bin/bash

#HALP Pull master and releases with automatic stash and switch.

set -e

. git_functions

prefix=$(githubuser)-

function pullthem {
    for b in `git branch | cut -c 3-`; do
        [[ $b = $prefix* ]] && continue
        git checkout $b
        git pull
    done
}

nicely pullthem
