#!/bin/bash

#HALP Create given branch with completion and automatic prefix and dashes, show menu for parent.

set -e

. git_functions

base=$(menu allbranches From)

name=$(IFS=-; echo "$(githubuser)-$*")

[[ kitchen-sink = $base ]] && name="$name-ks"

git checkout -b $name $base

cdtocorda

echo $base >.pb/$name
