#!/usr/bin/env python3

#HALP Create given branch with completion and dashes, show menu for parent.

from common import run, addparents, githubuser, args, AllBranches, menu

def main():
    _, base = menu([[n, ''] for n in AllBranches().names], 'From')
    name = '-'.join(args())
    run(['git', 'checkout', '-b', name, base])
    addparents(name, base)

if '__main__' == __name__:
    main()
