#!/usr/bin/env python3

#HALP Commit with the given args as message.

from common import run, args, isgitpol

def main():
    run(['git', 'commit', '-m', ' '.join((['WIP'] if isgitpol() else []) + args())])

if '__main__' == __name__:
    main()
