#!/usr/bin/env python3

#HALP Switch to the given branch, with completion.

from common import run, args, AllBranches, addparents

def main():
    name, = args()
    new = name not in AllBranches().names
    run(['git', 'checkout', name])
    if new:
        addparents(name, "origin/%s" % name) # FIXME: It might be ent not origin.

if '__main__' == __name__:
    main()
