#!/usr/bin/env python3

#HALP Switch to the given branch, with completion.

from common import *
import sys

def main():
    run(['git', 'checkout'] + sys.argv[1:])

if '__main__' == __name__:
    main()
