#!/bin/bash

#HALP Deploy and run the given demo.

set -e

. git_functions

cdtocorda

demoname=$1

shift

function tasknames {
    grep -o 'task\s[^(]*' | awk '{ print $2 }'
}

function deploytasks {
    grep Cordform samples/$demoname/build.gradle | tasknames
    echo SKIP
}

deploytask=$(menu deploytasks Deploy task)

[[ SKIP = $deploytask ]] || {
    ./gradlew samples:$demoname:clean
    ./gradlew samples:$demoname:$deploytask --stacktrace
    $(find ./samples/$demoname/build/nodes -name runnodes) --logging-level DEBUG "$@"
}

function runtasks {
    grep JavaExec samples/$demoname/build.gradle | tasknames
    echo QUIT
}

while true; do

    runtask=$(menu runtasks Run task)

    [[ QUIT = $runtask ]] && break

    ./gradlew samples:$demoname:$runtask

done
