#!/bin/bash

#HALP Deploy and run the given demo.

set -e

. git_functions

cdtocorda

demoname=$1

shift

function deploytasks {
    grep Cordform samples/$demoname/build.gradle | grep -o 'task[^(]*' | awk '{ print $2 }'
}

deploytask=$(menu deploytasks Deploy task)

./gradlew samples:$demoname:clean

./gradlew samples:$demoname:$deploytask --stacktrace

./samples/$demoname/build/nodes/runnodes "$@"

function runtasks {
    grep JavaExec samples/$demoname/build.gradle | grep -o 'task[^(]*' | awk '{ print $2 }'
}

while true; do

    runtask=$(menu runtasks Run task)

    ./gradlew samples:$demoname:$runtask

done
