#!/bin/bash

#HALP Deploy and run the given demo.

set -e

. git_functions

cdtocorda

demoname=$1

shift

function deploytasks {
    grep Cordform samples/$demoname/build.gradle | grep -o 'task[^(]*' | awk '{ print $2 }'
    echo SKIP
}

deploytask=$(menu deploytasks Deploy task)

[[ SKIP = $deploytask ]] || {
    ./gradlew samples:$demoname:clean
    ./gradlew samples:$demoname:$deploytask --stacktrace
    ./samples/$demoname/build/nodes/runnodes "$@"
}

function runtasks {
    grep JavaExec samples/$demoname/build.gradle | grep -o 'task[^(]*' | awk '{ print $2 }'
    echo QUIT
}

while true; do

    runtask=$(menu runtasks Run task)

    [[ QUIT = $runtask ]] && break

    ./gradlew samples:$demoname:$runtask

done
