#!/usr/bin/env python3

#HALP Diff from public branch.

from common import getpublic, args, chain, stderr

def main():
    parent = getpublic()
    stderr("Public branch: %s" % parent)
    chain(['git', 'diff', '-M25'] + args() + [parent])

if '__main__' == __name__:
    main()
