#!/bin/bash

set -e

function logged {
    echo "$@" >&2
    "$@"
}

docker ps -a

ids=$(docker ps -aq)

[[ "$ids" ]] && {
    logged docker stop $ids
    logged docker rm $ids
}

docker images

ids=$(docker images | tail -n +2 | ag -v '^(?:rabbitmq|python|redis) ' | awk '{ print $3 }')

[[ "$ids" ]] && {
    logged docker rmi $ids
}

docker volume ls

yes | logged docker volume prune
