#!/bin/bash

set -e

function logged {
    echo "$@" >&2
    "$@"
}

docker ps -a

ids=$(docker ps -aq)

[[ "$ids" ]] && {
    logged docker stop $ids
    logged docker rm $ids
}

docker images

ids=$(docker images -q)

[[ "$ids" ]] && {
    logged docker rmi $ids
}
