#!/bin/bash

#HALP Drop this branch.

set -ex

. git_functions

[[ "$1" != '-f' && "$(dxx)" ]] && {
    echo 'Unmerged changes!' >&2
    exit 1
}

git rebase --abort || true

[[ "$(git status --porcelain)" ]] && abandon

todrop=$(thisbranch)

unset b

v="$(allbranches)"

for next in $v $v; do

    [[ $b = $todrop ]] && break

    b=$next

done

co $next

git branch -D $todrop

cdtocorda

rm -fv .pb/$todrop
