#!/usr/bin/env python3

#HALP Add the top commit to the list of slammed commits.

from common import AllBranches, savecommits

def main():
    savecommits([AllBranches().branchcommits()[0][0]])

if '__main__' == __name__:
    main()
