#!/usr/bin/env python3

#HALP Diff from parent branch.

from common import pb, args, chain, stderr

def main():
    parent = pb()
    stderr("Parent branch: %s" % parent)
    chain(['git', 'diff', '-M25'] + args() + [parent])

if '__main__' == __name__:
    main()
