#!/usr/bin/env python3

#HALP Diff from parent branch.

from common import *

def main():
    parent = pb()
    print("Parent branch: %s" % parent, file = sys.stderr)
    chain(['git', 'diff', '-M25'] + args() + [parent])

if '__main__' == __name__:
    main()
