#!/bin/bash

#HALP Rebase on the given branch with completion, or parent with confirmation.

set -e

if [[ "$@" ]]; then
    args=("$@")
else
    args=($(pb))
    read -p "Press enter to rebase on: $args"
fi

git rebase "${args[@]}"
