#!/bin/bash

#HALP Why is this suddenly necessary?

set -ex

. git_functions

cdtocorda

function review {
    find .idea -name *.iml -exec ag -o '[^/]*-SNAPSHOT.jar' '{}' +
}

review

read -p 'Press enter to fix the build.'

find .idea -name *.iml -exec sed -i "s/[^\":]*-SNAPSHOT.jar://g;s:\"$HOME:\"\$USER_HOME\$:" '{}' +

review
