#!/usr/bin/env python3

#HALP Run ag on all build.gradle files.

from common import *
import sys

def main():
    sys.exit(subprocess.run(['find', '-name', 'build.gradle', '-exec', 'ag'] + args() + ['{}', '+']).returncode)

if '__main__' == __name__:
    main()
