#!/usr/bin/env python3

#HALP Run ag on all build.gradle files.

from common import *

def main():
    chain(['find', '-name', 'build.gradle', '-exec', 'ag'] + args() + ['{}', '+'])

if '__main__' == __name__:
    main()
