#!/usr/bin/env python3

#HALP Run the context gradlew.

from common import *

def main():
    sys.exit(subprocess.run([os.path.join(findproject(), 'gradlew')] + args()).returncode)

if '__main__' == __name__:
    main()
