#!/usr/bin/env python3

#HALP Run the context gradlew.

from common import chain, findproject, args
import os

def main():
    chain([os.path.join(findproject(), 'gradlew')] + args())

if '__main__' == __name__:
    main()
