#!/usr/bin/env python3

#HALP Stage all outgoing changes and show them.

from common import run, findproject, runpy

def main():
    run(['git', 'add', findproject()])
    runpy(['st'])

if '__main__' == __name__:
    main()
