#!/bin/bash

#HALP You're looking at it!

set -e

cd "$(dirname "$(readlink -f "$0")")"

prefix='#HALP'

for script in *; do

    halp="$(grep "^$prefix" $script)" && printf "%-9s%s\n" $script "${halp:${#prefix}}"

done
