#!/bin/bash

#HALP Merge master into all PRs.

set -ex

. git_functions

prefix=$(githubuser)-

function mergethem {
    for b in $(publicbranches); do
        [[ $b = $prefix* ]] || continue
        git checkout $b
        git merge --no-edit master
    done
}

nicely mergethem
