#!/usr/bin/env python3

#HALP Merge master into all PRs and carrion.

from common import findproject, nicely, allbranches, ispublic, stderr, parents, run
import os

def mergethem():
    remaining = allbranches()
    branchtoparents = {b: parents(remaining, b) for b in remaining}
    allparents = set(p for parents in branchtoparents.values() for p in parents)
    def update(b):
        run(['git', 'checkout', b])
        parents = branchtoparents[b]
        if b in allparents or ispublic():
            for p in parents:
                run(['git', 'merge', '--no-edit', p])
        else:
            p, = parents
            run(['git', 'rebase', p])
    done = set()
    while remaining:
        stderr("Remaining: %s" % ' '.join(remaining))
        def g():
            for b in remaining:
                for p in branchtoparents[b]:
                    if not (p.startswith('origin/') or p in done):
                        yield b
                        break
                else:
                    update(b)
                    done.add(b)
        remaining2 = list(g())
        if remaining2 == remaining:
            raise Exception("Still remain: %s" % remaining)
        remaining = remaining2

def main():
    os.chdir(findproject()) # XXX: Why?
    nicely(mergethem)

if '__main__' == __name__:
    main()
