#!/usr/bin/env python3

#HALP Reinstall corda gradle plugins.

from common import findproject, runpy
import os

def main():
    projectdir = findproject()
    runpy(['gradle', '-u', 'clean', 'install'], cwd = os.path.join(projectdir, 'gradle-plugins', 'publish-utils'))
    runpy(['gradle', 'clean', 'install'], cwd = os.path.join(projectdir, 'gradle-plugins'))

if '__main__' == __name__:
    main()
