#!/bin/bash

#HALP Create a master-based branch from this kitchen-sink-based one.

set -e

. git_functions

base=kitchen-sink

[[ $base = $(pb) ]] || {
    echo Parent is not $base'!' >&2
    exit 1
}

ids=($(git cherry $base | while read _ id; do echo $id; done))

name=$(thisbranch)

if [[ $name = *-ks ]]; then
    name=${name%-ks}
else
    name=${name}-master # TODO: Retire this scheme.
fi

git checkout -b $name master

git cherry-pick ${ids[@]}
