#!/bin/bash

#HALP Publish this branch, accepts push options.

set -ex

. git_functions

name=$(thisbranch)

cdtocorda

[[ kitchen-sink = $(cat .pb/$name) ]] && {
    echo 'Refusing to push kitchen-sink based branch.' >&2
    exit 1
}

git push -u origin $name "$@"
