#!/bin/bash

#HALP Publish this branch, accepts push options.

set -e

. git_functions

name=$(thisbranch)

[[ kitchen-sink = $(pb) ]] && {
    echo 'Refusing to push kitchen-sink based branch.' >&2
    exit 1
}

git push -u origin $name "$@"
