#!/usr/bin/env python3

#HALP Remove all untracked items, including the git-ignored.

from common import findproject, run

def main():
    run(['git', 'clean', '-xdi'], cwd = findproject())

if '__main__' == __name__:
    main()
