#!/usr/bin/env python3

import sys, subprocess, re

pattern = re.compile('latest|.+[.]latest')

def main():
    spec, = sys.argv[1:]
    slash = spec.index('/')
    colon = spec.rindex(':')
    tag = spec[colon + 1:]
    if pattern.fullmatch(tag) is None:
        raise Exception('REFUSAL!')
    subprocess.check_call(['bash', '-ic', 'aws ecr batch-delete-image --repository-name "$1" --image-ids "$2"', 'ecr', spec[slash + 1:colon], f"imageTag={tag}"])
    subprocess.check_call(['docker', 'push', spec])

if '__main__' == __name__:
    main()
