#!/usr/bin/env python3

#HALP Show a commit that was listed by st.

from common import args, showmenu, menu, chain, AllBranches

def main():
    items = AllBranches().branchcommits()
    v = args()
    if v:
        n, = v
        n = int(n)
        id = showmenu(items, False)[n]
    else:
        _, id = menu(items, 'Show which commit')
    chain(['git', 'show', id])

if '__main__' == __name__:
    main()
