#!/usr/bin/env python3

#HALP Reset branch to given commit number.

from common import branchcommits, args, showmenu, chain, pb

def main():
    items = branchcommits() + [[pb(), '']]
    n, = args()
    n = int(n)
    id = showmenu(items, False)[n]
    chain(['git', 'reset', '--hard', id])

if '__main__' == __name__:
    main()
