#!/bin/bash

#HALP Semi-interactively squash a most-recent chunk of commits.

set -e

base=$(pb)

ids=($(git cherry $base | tac | while read _ id; do echo $id; done))

function cherry {
    for id in ${ids[@]}; do
        echo $id "$(git log -n 1 --format=%s $id)"
    done
}

. git_functions

id=$(menu cherry Which commit should absorb all newer commits)

git reset --soft $id~1

git commit -c $id
