#!/usr/bin/env python3

#HALP Unpublish this branch.

from common import *

def main():
    subprocess.run(['git', 'push', 'origin', '--delete', thisbranch()]) # Idempotent.
    chain(['git', 'branch', '--unset-upstream'])

if '__main__' == __name__:
    main()
