#!/usr/bin/env python3

#HALP Unpublish this branch.

from common import *
import sys

def main():
    subprocess.run(['git', 'push', 'origin', '--delete', thisbranch()])
    sys.exit(subprocess.run(['git', 'branch', '--unset-upstream']).returncode)

if '__main__' == __name__:
    main()
