#!/usr/bin/env python3

#HALP Cherry-pick commits lost in a previous slam.

from common import findproject, thisbranch, infodirname, chain, os

def main():
    path = os.path.join(findproject(), infodirname, "%s slammed" % thisbranch())
    with open(path) as f:
        commits = f.read().splitlines()
    commits.reverse()
    chain(['git', 'cherry-pick'] + commits)

if '__main__' == __name__:
    main()
